### PR TITLE
im making a mess, so all in one

### LINKED ISSUE #14: UI becomes unresponsive once the menu is open.
I have a problem in which once I get into the menu to select any sort of item, mouse clicks become totally unresponsive within the game. On the screen shown in the attachment, I can mouse over menu items, but clicking the left button, or hitting enter, does nothing.

I am running the latest versions of extendedmode, es_essentials, and the required esx components for this to run, and have verified they are all loading correctly. 

I am also seeing the following displayed in my server output, if it is of any help.

`[MariaDB:10.5.8-MariaDB-1:10.5.8+maria~focal] [WARNING] [esx_skin] [642ms] UPDATE users SET skin = ? WHERE identifier = ? : ["{\"beard_4\":7,\"arms\":1,\"chain_2\":0,\"decals_1\":0,\"chest_2\":6,\"makeup_4\":0,\"lipstick_1\":0,\"eye_color\":4,\"bracelets_1\":-1,\"tshirt_1\":57,\"bodyb_2\":5,\"bproof_1\":0,\"glasses_2\":1,\"bags_1\":0,\"shoes_2\":4,\"hair_color_1\":8,\"eyebrows_2\":5,\"hair_color_2\":9,\"hair_2\":3,\"complexion_2\":4,\"pants_2\":1,\"makeup_3\":0,\"age_2\":4,\"chest_1\":5,\"blush_3\":0,\"bags_2\":0,\"age_1\":3,\"helmet_2\":0,\"mask_2\":0,\"beard_3\":10,\"pants_1\":1,\"watches_1\":-1,\"ears_2\":0,\"arms_2\":0,\"blush_1\":0,\"bodyb_1\":3,\"makeup_2\":0,\"hair_1\":1,\"glasses_1\":8,\"helmet_1\":-1,\"bproof_2\":0,\"bracelets_2\":0,\"beard_1\":6,\"moles_2\":3,\"sun_1\":4,\"blemishes_1\":4,\"mask_1\":0,\"eyebrows_4\":5,\"torso_1\":14,\"moles_1\":4,\"complexion_1\":4,\"ears_1\":-1,\"lipstick_4\":0,\"lipstick_2\":0,\"eyebrows_1\":4,\"torso_2\":1,\"shoes_1\":51,\"face\":6,\"sex\":0,\"blush_2\":0,\"skin\":1,\"chest_3\":5,\"blemishes_2\":5,\"sun_2\":2,\"watches_2\":0,\"decals_2\":0,\"tshirt_2\":0,\"chain_1\":9,\"lipstick_3\":0,\"beard_2\":8,\"makeup_1\":0,\"eyebrows_3\":6}","steam:***********"]`

### PR DESCRIPTION
**Pull request by iSentrie**
fixes #14

### CODE REVIEW

**Comment by DonJoan** [comment]
If you look down you will see that it has already been uploaded and corrected, but we are waiting for the author

**Comment by iSentrie** [comment]
um im pretty much blind tho, about what ur talking rn?

**Comment by GMA950** [comment]
done

**Comment by iSentrie** [comment]
gg

**Pull request merged**
