### PR TITLE
Update main.lua

### PR DESCRIPTION
**Pull request by DonJoan**

### CODE REVIEW

**Review by GMA950 — APPROVED** [review]

**Comment by GMA950** [comment]
updated

**Comment by DonJoan** [comment]
Do you want me to clear the code?

**Comment by GMA950** [comment]
of course, i don't have the time for coding or playing fivem anymore, if you can help with this script, you´re welcome

**Comment by DonJoan** [comment]
I would very much like ui to be a little more attractive and sexy 😁 Something similar to cui character

But I'm not good at that

**Pull request merged**
